Repository canonical/docs.ubuntu.com, pull requests merged in 2018-08, with the labels that each got.

#166 fixed typos on docs.u.c homepage
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#168 Add entrypoint for talisker gevent workers
  Dockerfile
  entrypoint
  package.json
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#169 Bump documentation-builder to 1.6.0
  requirements.txt
Labels: Review: Code +1

#172 Add net-tools
  Dockerfile
  requirements.txt
Labels: Review: Code needed

#173 Update talisker entrypoint
  entrypoint
Labels: Review: Code +1
