Repository canonical/docs.ubuntu.com, pull requests merged in 2019-02, with the labels that each got.

#186 Update to Vanilla v1.8
  package.json
  static/sass/_patterns_navigation.scss
  templates/includes/layout.html
  templates/index.html
  templates/search.html
  yarn.lock
Labels: Review: Code +1, Review: QA +1

#200 Use our standard renovate.json
  renovate.json
Labels: Review: Code +1

#207 Redirect landscape-api to api
  redirects.yaml
Labels: Review: Code needed, Review: QA needed
