Repository canonical/docs.ubuntu.com, pull requests merged in 2020-07, with the labels that each got.

#249 Update spelling of OpenStack, remove conjure-ip docs
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#251 Rename deploy to konf
  konf/site.yaml
Labels: Review: QA +1

#252 Redirections for core, phone and security-certs
  konf/site.yaml
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#253 Add Sentry DSN to site.yaml
  konf/site.yaml
Labels: Review: Code +1
